# Permalinks
permalink:        pretty

# Setup
title:            'City of Austin '
tagline:          'atxopendata.rocks'
description:      ''
url:            https://happinessk.github.io/blah2/

author:
  name:           ''
  url:            ''

# Custom vars
version:          0.0.0

github:
  repo:           
